# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\logger.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(337, 242)
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/app_icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("color: rgb(41, 45, 62);\n"
"background-color: rgb(41, 45, 62);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.QinfoLabel_23 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.QinfoLabel_23.setFont(font)
        self.QinfoLabel_23.setStyleSheet("color: rgb(255, 255, 255);")
        self.QinfoLabel_23.setAlignment(QtCore.Qt.AlignCenter)
        self.QinfoLabel_23.setObjectName("QinfoLabel_23")
        self.verticalLayout.addWidget(self.QinfoLabel_23)
        self.QPLCInfo = QtWidgets.QLabel(self.centralwidget)
        self.QPLCInfo.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.QPLCInfo.setFont(font)
        self.QPLCInfo.setStyleSheet("color: rgb(41, 45, 62);\n"
"background-color: rgb(255, 0, 0);")
        self.QPLCInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.QPLCInfo.setObjectName("QPLCInfo")
        self.verticalLayout.addWidget(self.QPLCInfo)
        self.horizontalLayout_14.addLayout(self.verticalLayout)
        self.horizontalLayout_14.setStretch(0, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.QinfoLabel_21 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.QinfoLabel_21.setFont(font)
        self.QinfoLabel_21.setStyleSheet("color: rgb(255, 255, 255);")
        self.QinfoLabel_21.setObjectName("QinfoLabel_21")
        self.horizontalLayout_2.addWidget(self.QinfoLabel_21)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.Qexit = QtWidgets.QPushButton(self.centralwidget)
        self.Qexit.setEnabled(True)
        self.Qexit.setStyleSheet(":enabled {color:rgb(255, 255, 255); background-color: rgb(65, 72, 99)} \n"
":disabled {color:rgb(150, 150, 180); background-color:rgb(88, 96, 104) }")
        self.Qexit.setObjectName("Qexit")
        self.horizontalLayout_13.addWidget(self.Qexit)
        self.horizontalLayout_13.setStretch(0, 7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.verticalLayout_3.setStretch(0, 8)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(3, 1)
        self.verticalLayout_3.setStretch(4, 9)
        self.horizontalLayout_15.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_15, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 337, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "System logger"))
        self.QinfoLabel_23.setText(_translate("MainWindow", "PLC communication"))
        self.QPLCInfo.setText(_translate("MainWindow", "Inactive"))
        self.QinfoLabel_21.setText(_translate("MainWindow", "Log file in: DocumentsLOG"))
        self.Qexit.setText(_translate("MainWindow", "EXIT"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
